package org.example.Lab3;

public enum Topics {
    TEMPERATURE,
    PRESSURE,
    CONSUMPTION_PER_MIN,
    CONSUMPTION_PER_10,
    CONSUMPTION_PER_HR,
    CONSUMPTION_PER_DAY,
    CONSUMPTION_PER_WEEK,
    CONSUMPTION_PER_MONTH,
    CONSUMPTION_PER_YEAR
}
